AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Example API
Resources:
  SampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      CodeUri: ./func.d
      Runtime: provided
      Layers:
        - !Sub "arn:aws:lambda:ap-northeast-1:${AWS::AccountId}:layer:layer-eks-kubectl-layer-stack:2"
      MemorySize: 512
      # Policies: 
      #   - AWSLambdaBasicExecutionRole
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LambdaEKSAdminRole"
      Timeout: 10


Outputs:
  LambdaArn:
    Description: Lambda ARN
    Value: !GetAtt SampleFunction.Arn
    Export:
      Name: !Sub 'LambdaArn-${AWS::StackName}'